import type { Runner } from '../advisor/types';
import { unitOf } from './advisor';

/**
 * Generate ready-to-paste CI config that applies an optimal split: one
 * parallel job per shard, each running EXACTLY its spec list (duration-optimal,
 * from ShardPlan.specs) — closing the loop from recommendation to real cloud
 * execution. `--shard=i/N` splits by test count, so it cannot express this;
 * explicit per-job spec lists can, in any runner. Each job keeps its own
 * report, which is the advisor's preferred input for the next analysis.
 */

function assertSpecs(specs: string[][]): void {
  if (specs.length === 0 || specs.some((list) => list.length === 0)) {
    throw new RangeError('specs must contain at least one non-empty spec list per shard');
  }
}

/** The run command for one shard: its exact spec list, emitting this shard's report. */
function runCommand(runner: Runner, list: string[], shard: number): string {
  return runner === 'cypress'
    ? `npx cypress run --reporter mochawesome --reporter-options "reportDir=reports,overwrite=false,html=false,json=true" --spec "${list.join(',')}"`
    : `npx playwright test ${list.join(' ')} --reporter=json > shard-${shard}.json`;
}

/** GitHub Actions workflow: one job per shard, each running its exact spec list. */
export function toGitHubActions(specs: string[][], runner: Runner): string {
  assertSpecs(specs);
  const n = specs.length;
  const jobs = specs
    .map((list, i) => {
      const shard = i + 1;
      const reportPath = runner === 'cypress' ? 'reports/' : `shard-${shard}.json`;
      const unit = unitOf(runner);
      return `  shard-${shard}:
    name: ${unit[0].toUpperCase() + unit.slice(1)} ${shard}/${n} (optimal split)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci${runner === 'playwright' ? '\n      - run: npx playwright install --with-deps' : ''}
      - name: Run this shard's specs
        run: ${runCommand(runner, list, shard)}
      - name: Upload this shard's report (feed all of them back to the advisor)
        if: \${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: shard-${shard}
          path: ${reportPath}
          retention-days: 7`;
    })
    .join('\n');

  return `# Generated by CI Shard Advisor — each job runs its duration-optimal spec list.
name: Tests (optimal split)
on:
  push:
    branches: [main]
  pull_request:
jobs:
${jobs}
`;
}

/** Bitbucket Pipelines: one parallel step per shard, each running its exact spec list. */
export function toBitbucketPipelines(specs: string[][], runner: Runner): string {
  assertSpecs(specs);
  const n = specs.length;
  const steps = specs
    .map((list, i) => {
      const shard = i + 1;
      const artifact = runner === 'cypress' ? 'reports/**' : `shard-${shard}.json`;
      const unit = unitOf(runner);
      return `        - step:
            name: ${unit[0].toUpperCase() + unit.slice(1)} ${shard}/${n} (optimal split)
            script:
              - npm ci${runner === 'playwright' ? '\n              - npx playwright install --with-deps' : ''}
              - ${runCommand(runner, list, shard)}
            artifacts:
              - ${artifact}`;
    })
    .join('\n');

  return `# Generated by CI Shard Advisor — each step runs its duration-optimal spec list.
image: node:20
pipelines:
  default:
    - parallel:
${steps}
`;
}
